### PR TITLE
Revamped English Localization

### PR DESCRIPTION
**Pull request by DatBisa**
I've went and started a complete overhaul of the game's English Translation to be more appropriate of a polished game.
I have yet to change any campaign dialogue.

### CODE REVIEW

**Comment by satofumi** [comment]
Thank you for correcting the English!
Sorry for the delay in noticing this, as I usually use BitBucket instead of GitHub.  I would like to list your contribution in the credits, can I use the name BLPFBisa? If you prefer another name, please let me know.
Then again, let me thank you for the translation. Thank you very much!

**Comment by DatBisa** [comment]
Using the game as a template, please credit as

```
Localization
    - Glimmer
           Bisa (English)
```

I'll update you when a website link becomes available, and I might also soon start work on a german localization.

**Comment by DatBisa** [comment]
I've made a few more error corrections on my fork. Do I create a separate pull request, or can you merge them directly?

**Comment by satofumi** [comment]
Could you please create a pull request so that I can log the contributions you have made?

**Comment by satofumi** [comment]
I will also correct the message in the credits.

**Comment by DatBisa** [comment]
New Pull Request created!
How hard would it be to add a German localization? I'm from there, and now that I have a full English localization, translating it into German would be trivial.

**Comment by satofumi** [comment]
Thank you for the offer.
Adding a new language is easy, for example, create a German.txt file that is a copy of the English.txt file in the Languages folder of the folder where BonsaiCastles.exe is located, and it will be used by the game.
The location of the exe file can be reached from the game's properties in Steam.
If I import it by pull request, it will be reflected in other people's games as well.

**Comment by satofumi** [comment]
I forgot to mention that pressing the F5 key during a game will reload the language file and reflect it. (Not reflected for some).

**Pull request merged**
